# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_K67b9dUMsHl068cRbr5qs1eIQNJxiW
"""

# Cell 1 — install
!pip install fastapi uvicorn gradio requests -q

# Cell 2 — run
!python hospital_bed_app.py

# ╔══════════════════════════════════════════════════════════════════╗
# ║   Hospital Bed Allocation — Complete Self-Contained Colab App   ║
# ║   RL Environment + FastAPI Backend + Gradio UI (one file)       ║
# ║                                                                  ║
# ║   SETUP (run once in Colab):                                    ║
# ║     !pip install fastapi uvicorn gradio requests -q             ║
# ║                                                                  ║
# ║   LAUNCH:                                                        ║
# ║     !python hospital_bed_app.py                                 ║
# ║     → Opens a public gradio.live URL                            ║
# ╚══════════════════════════════════════════════════════════════════╝

import threading
import time
import random
import requests
import gradio as gr
import uvicorn
from fastapi import FastAPI

# ════════════════════════════════════════════════════════════════════
#  1.  RL ENVIRONMENT
#
#  Goal: allocate limited ICU beds to patients, prioritising those
#        with the highest severity scores.
#
#  State:  list of patients with id, severity (1-10), arrival type
#  Action: patient id to assign a bed to
#  Reward: +severity (+2 Emergency bonus, +1 Urgent bonus)
#          -5  if patient id does not exist
#          -10 if no beds remain
#  Episode ends when all beds filled OR all patients served.
# ════════════════════════════════════════════════════════════════════

class HospitalEnv:
    def __init__(self, n_beds: int = 5, n_patients: int = 10):
        self.n_beds = n_beds
        self.n_patients = n_patients
        self.beds_left = n_beds
        self.patients: list[dict] = []
        self.total_reward = 0.0
        self.steps_taken = 0
        self.done = False

    def reset(self) -> dict:
        self.beds_left = self.n_beds
        self.total_reward = 0.0
        self.steps_taken = 0
        self.done = False
        self.patients = [
            {
                "id": i,
                "severity": round(random.uniform(1.0, 10.0), 1),
                "name": f"Patient-{i:02d}",
                "arrival": random.choice(["Emergency", "Urgent", "Standard"]),
            }
            for i in range(self.n_patients)
        ]
        return {
            "available_beds": self.beds_left,
            "total_patients": self.n_patients,
            "patients": list(self.patients),
        }

    def step(self, action: int) -> dict:
        if self.done:
            return {
                "reward": 0, "remaining_beds": self.beds_left,
                "done": True, "patients_left": list(self.patients),
                "total_reward": round(self.total_reward, 2),
                "steps": self.steps_taken,
                "error": "Episode is done. Please reset.",
            }

        if self.beds_left <= 0:
            self.done = True
            return {
                "reward": -10, "remaining_beds": 0,
                "done": True, "patients_left": list(self.patients),
                "total_reward": round(self.total_reward, 2),
                "steps": self.steps_taken,
                "error": "No beds remaining.",
            }

        patient = next((p for p in self.patients if p["id"] == action), None)
        if patient is None:
            reward = -5.0
            self.total_reward += reward
            self.steps_taken += 1
            return {
                "reward": reward, "remaining_beds": self.beds_left,
                "done": False, "patients_left": list(self.patients),
                "total_reward": round(self.total_reward, 2),
                "steps": self.steps_taken,
                "error": f"Patient {action} not found.",
            }

        reward = patient["severity"]
        if patient["arrival"] == "Emergency":
            reward += 2.0
        elif patient["arrival"] == "Urgent":
            reward += 1.0
        reward = round(reward, 2)

        self.total_reward = round(self.total_reward + reward, 2)
        self.patients = [p for p in self.patients if p["id"] != action]
        self.beds_left -= 1
        self.steps_taken += 1
        self.done = (self.beds_left == 0) or (len(self.patients) == 0)

        return {
            "reward": reward,
            "remaining_beds": self.beds_left,
            "done": self.done,
            "patients_left": list(self.patients),
            "total_reward": self.total_reward,
            "steps": self.steps_taken,
            "assigned_patient": patient,
        }


# ════════════════════════════════════════════════════════════════════
#  2.  FASTAPI BACKEND
# ════════════════════════════════════════════════════════════════════

app = FastAPI(title="Hospital Bed Allocation API")
env = HospitalEnv(n_beds=5, n_patients=10)


@app.get("/health")
def health():
    return {"status": "ok"}

@app.get("/reset")
def reset():
    return env.reset()

@app.post("/step")
def step(action: int):
    return env.step(action)


def run_server():
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="error")


# ════════════════════════════════════════════════════════════════════
#  3.  START BACKEND IN BACKGROUND THREAD
# ════════════════════════════════════════════════════════════════════

def wait_for_backend(retries=30, delay=0.4):
    for _ in range(retries):
        try:
            if requests.get("http://127.0.0.1:8000/health", timeout=1).status_code == 200:
                return True
        except Exception:
            pass
        time.sleep(delay)
    return False


print("⏳ Starting backend server...")
threading.Thread(target=run_server, daemon=True).start()

if wait_for_backend():
    print("✅ Backend ready at http://127.0.0.1:8000")
else:
    print("❌ Backend failed to start — check for port conflicts")


# ════════════════════════════════════════════════════════════════════
#  4.  GRADIO UI
# ════════════════════════════════════════════════════════════════════

BASE_URL = "http://127.0.0.1:8000"
patient_table_data: list[list] = []


def reset_env():
    global patient_table_data
    try:
        res = requests.get(f"{BASE_URL}/reset", timeout=5).json()
    except Exception as e:
        return (f"❌ Backend error: {e}", [], "—", "—", "—", "—")

    patient_table_data = [
        [p["id"], p["name"], p["severity"], p["arrival"], "⏳ Pending"]
        for p in res.get("patients", [])
    ]
    return (
        "✅ New episode started. Assign beds using the Patient IDs shown below.",
        patient_table_data,
        str(res.get("available_beds", "—")),
        str(res.get("total_patients", "—")),
        "0",
        "0.00",
    )


def assign_bed(patient_id_str: str):
    global patient_table_data

    if not patient_id_str.strip():
        return ("⚠️ Enter a Patient ID first.", patient_table_data,
                gr.update(), gr.update(), gr.update(), gr.update())
    try:
        patient_id = int(patient_id_str.strip())
    except ValueError:
        return ("⚠️ Patient ID must be a whole number.", patient_table_data,
                gr.update(), gr.update(), gr.update(), gr.update())

    try:
        res = requests.post(
            f"{BASE_URL}/step", params={"action": patient_id}, timeout=5
        ).json()
    except Exception as e:
        return (f"❌ Backend error: {e}", patient_table_data,
                gr.update(), gr.update(), gr.update(), gr.update())

    if "error" in res:
        return (f"⚠️ {res['error']}", patient_table_data,
                gr.update(), gr.update(), gr.update(), gr.update())

    reward        = res.get("reward", 0)
    remaining     = res.get("remaining_beds", "—")
    done          = res.get("done", False)
    patients_left = res.get("patients_left", [])
    total_reward  = res.get("total_reward", 0)
    assigned      = res.get("assigned_patient", {})

    for row in patient_table_data:
        if row[0] == patient_id:
            row[4] = "✅ Assigned"
            break

    assigned_count = sum(1 for r in patient_table_data if r[4] == "✅ Assigned")
    icon = "🟢" if reward > 0 else "🔴"
    arrival = assigned.get("arrival", "")
    episode_note = "  🏁 Episode complete — press Reset to start again." if done else ""
    log = (
        f"{icon}  Patient {patient_id} ({arrival}) assigned  "
        f"|  Reward: +{reward}  |  Beds left: {remaining}{episode_note}"
    )

    return (
        log,
        list(patient_table_data),
        str(remaining),
        str(len(patients_left)),
        str(assigned_count),
        str(total_reward),
    )


# ── CSS ─────────────────────────────────────────────────────────────

CSS = """
@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&family=Syne:wght@400;700;800&display=swap');

body, .gradio-container {
    font-family: 'Syne', sans-serif !important;
    background: #0d1117 !important;
    color: #e6edf3 !important;
}
.gradio-container { max-width:960px!important; margin:0 auto!important; padding:2rem 1.5rem!important; }

#app-header { border-bottom:1px solid #21262d; margin-bottom:2rem; padding-bottom:1.2rem; }
#app-header h1 { font-size:1.9rem; font-weight:800; letter-spacing:-0.5px; color:#fff; margin:0 0 .25rem; }
#app-header p  { font-size:.8rem; color:#8b949e; margin:0; font-family:'JetBrains Mono',monospace; }

.stat-card { background:#161b22!important; border:1px solid #21262d!important; border-radius:10px!important; padding:1rem 1.25rem!important; }
.stat-card label { font-size:.68rem!important; text-transform:uppercase!important; letter-spacing:1.2px!important; color:#8b949e!important; font-family:'JetBrains Mono',monospace!important; }
.stat-card textarea, .stat-card input { font-size:1.7rem!important; font-weight:700!important; color:#58a6ff!important; background:transparent!important; border:none!important; padding:0!important; font-family:'Syne',sans-serif!important; box-shadow:none!important; }

.action-panel { background:#161b22!important; border:1px solid #21262d!important; border-radius:10px!important; padding:1.25rem!important; }
.section-label { font-size:.68rem!important; text-transform:uppercase!important; letter-spacing:1.2px!important; color:#8b949e!important; font-family:'JetBrains Mono',monospace!important; margin-bottom:.4rem!important; }

button { font-family:'Syne',sans-serif!important; font-weight:700!important; border-radius:8px!important; }
.primary-btn   { background:#238636!important; color:#fff!important; border:none!important; font-size:.9rem!important; }
.primary-btn:hover { background:#2ea043!important; }
.secondary-btn { background:transparent!important; color:#8b949e!important; border:1px solid #30363d!important; font-family:'JetBrains Mono',monospace!important; font-size:.82rem!important; }
.secondary-btn:hover { color:#e6edf3!important; border-color:#58a6ff!important; }

input[type=text], .gr-text-input input { background:#0d1117!important; border:1px solid #30363d!important; border-radius:8px!important; color:#e6edf3!important; font-family:'JetBrains Mono',monospace!important; font-size:.9rem!important; }
input[type=text]:focus { border-color:#58a6ff!important; box-shadow:0 0 0 3px rgba(88,166,255,.1)!important; }

.log-box textarea { background:#0d1117!important; border:1px solid #21262d!important; border-radius:8px!important; color:#7ee787!important; font-family:'JetBrains Mono',monospace!important; font-size:.82rem!important; line-height:1.6!important; }

.gr-dataframe table { background:#0d1117!important; border:1px solid #21262d!important; font-family:'JetBrains Mono',monospace!important; font-size:.82rem!important; width:100%!important; }
.gr-dataframe th    { background:#161b22!important; color:#8b949e!important; text-transform:uppercase!important; letter-spacing:1px!important; font-size:.68rem!important; border-bottom:1px solid #21262d!important; padding:.5rem 1rem!important; }
.gr-dataframe td    { border-bottom:1px solid #161b22!important; color:#e6edf3!important; padding:.55rem 1rem!important; }
"""

# ── Layout ──────────────────────────────────────────────────────────

with gr.Blocks(css=CSS, title="Hospital Bed Allocation") as demo:

    gr.HTML("""
    <div id="app-header">
        <h1>🏥 Hospital Bed Allocation</h1>
        <p>Reinforcement Learning Environment · ICU Triage · Meta × Hugging Face Hackathon</p>
    </div>
    """)

    with gr.Row():
        stat_beds     = gr.Textbox(label="Beds Available",   value="—", interactive=False, elem_classes=["stat-card"])
        stat_patients = gr.Textbox(label="Patients Waiting", value="—", interactive=False, elem_classes=["stat-card"])
        stat_assigned = gr.Textbox(label="Beds Assigned",    value="—", interactive=False, elem_classes=["stat-card"])
        stat_reward   = gr.Textbox(label="Total Reward",     value="—", interactive=False, elem_classes=["stat-card"])

    gr.HTML("<div style='height:1.25rem'></div>")

    with gr.Group(elem_classes=["action-panel"]):
        gr.HTML("<p class='section-label'>Actions</p>")
        with gr.Row():
            reset_btn     = gr.Button("↺  Reset Episode", elem_classes=["secondary-btn"], size="sm")
            patient_input = gr.Textbox(
                placeholder="Enter Patient ID (e.g. 4)",
                label="", scale=2, container=False
            )
            assign_btn = gr.Button("Assign Bed  →", elem_classes=["primary-btn"], size="sm", scale=1)

    gr.HTML("<div style='height:1rem'></div>")
    gr.HTML("<p class='section-label'>Activity log</p>")
    log_box = gr.Textbox(
        value="Press 'Reset Episode' to begin.",
        label="", lines=2, interactive=False, elem_classes=["log-box"]
    )

    gr.HTML("<div style='height:1rem'></div>")
    gr.HTML("<p class='section-label'>Patient queue</p>")
    patient_table = gr.Dataframe(
        headers=["ID", "Name", "Severity (1–10)", "Arrival Type", "Status"],
        datatype=["number", "str", "number", "str", "str"],
        value=[],
        interactive=False,
        wrap=False,
    )

    outputs = [log_box, patient_table, stat_beds, stat_patients, stat_assigned, stat_reward]
    reset_btn.click(fn=reset_env, outputs=outputs)
    assign_btn.click(fn=assign_bed, inputs=[patient_input], outputs=outputs)
    patient_input.submit(fn=assign_bed, inputs=[patient_input], outputs=outputs)


# ════════════════════════════════════════════════════════════════════
#  5.  LAUNCH
# ════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    demo.launch(share=True)   # share=True → public URL works in Colab

